In [4]:
import pandas as pd

In [5]:
students = {
    'std_id': [12345, 12346, 12347, 12348],
    'fname': ['Dilshad', 'Adam', 'Chris', 'Azad'],
    'lname': ['Abdulla', 'George', 'Smith', 'Abdulla'],
    'email': ['dilshad.a73@email.com', 'adam_george@email.com', 'chris_smith@email.com', 'azad_abdulla@email.com'],
    'city': ['Berlin', 'Roma', 'Paris', 'London']
}

In [6]:
df = pd.DataFrame(students)

In [7]:
df

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
1   12346     Adam   George   adam_george@email.com    Roma
2   12347    Chris    Smith   chris_smith@email.com   Paris
3   12348     Azad  Abdulla  azad_abdulla@email.com  London

In [8]:
df.sort_values(by='fname')

   std_id    fname    lname                   email    city
1   12346     Adam   George   adam_george@email.com    Roma
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
2   12347    Chris    Smith   chris_smith@email.com   Paris
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin

In [9]:
df.sort_values(by='lname')

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
1   12346     Adam   George   adam_george@email.com    Roma
2   12347    Chris    Smith   chris_smith@email.com   Paris

In [11]:
# ascending use for reverse if is True means following by lname but if is False not reverese it by lname
df.sort_values(by='fname', ascending=False)

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
2   12347    Chris    Smith   chris_smith@email.com   Paris
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
1   12346     Adam   George   adam_george@email.com    Roma

In [12]:
df.sort_values(by='fname', ascending=True)

   std_id    fname    lname                   email    city
1   12346     Adam   George   adam_george@email.com    Roma
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
2   12347    Chris    Smith   chris_smith@email.com   Paris
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin

In [14]:
# this is sorted by lname first when all lname done than follow fname of course if ascending=False
df.sort_values(by=['lname', 'fname'], ascending=False)

   std_id    fname    lname                   email    city
2   12347    Chris    Smith   chris_smith@email.com   Paris
1   12346     Adam   George   adam_george@email.com    Roma
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
3   12348     Azad  Abdulla  azad_abdulla@email.com  London

In [15]:
# it not sorted data by lname or fname because ascending=True
df.sort_values(by=['lname', 'fname'], ascending=True)

   std_id    fname    lname                   email    city
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
1   12346     Adam   George   adam_george@email.com    Roma
2   12347    Chris    Smith   chris_smith@email.com   Paris

In [16]:
df.sort_values(by=['lname', 'fname'], ascending=False)

   std_id    fname    lname                   email    city
2   12347    Chris    Smith   chris_smith@email.com   Paris
1   12346     Adam   George   adam_george@email.com    Roma
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
3   12348     Azad  Abdulla  azad_abdulla@email.com  London

In [17]:
# this is sort all lname first
df.sort_values(by=['lname', 'fname'])

   std_id    fname    lname                   email    city
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
1   12346     Adam   George   adam_george@email.com    Roma
2   12347    Chris    Smith   chris_smith@email.com   Paris

In [18]:
# this is sort all lname first
df.sort_values(by=['city', 'lname', 'fname'])

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
2   12347    Chris    Smith   chris_smith@email.com   Paris
1   12346     Adam   George   adam_george@email.com    Roma

In [20]:
# the sort doesn't work here because ascending=True
df.sort_values(by=['city', 'lname', 'fname'], ascending=True)

   std_id    fname    lname                   email    city
1   12346     Adam   George   adam_george@email.com    Roma
2   12347    Chris    Smith   chris_smith@email.com   Paris
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin

In [21]:
# the sort follow city first and it work here because ascending=False
df.sort_values(by=['city', 'lname', 'fname'], ascending=True)

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
2   12347    Chris    Smith   chris_smith@email.com   Paris
1   12346     Adam   George   adam_george@email.com    Roma

In [22]:
df.sort_values(by=['city', 'lname'], ascending=[False, True])

   std_id    fname    lname                   email    city
1   12346     Adam   George   adam_george@email.com    Roma
2   12347    Chris    Smith   chris_smith@email.com   Paris
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin

In [23]:
df.sort_values(by=['city', 'lname'], ascending=[True, False])

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
2   12347    Chris    Smith   chris_smith@email.com   Paris
1   12346     Adam   George   adam_george@email.com    Roma

In [24]:
df.sort_values(by=['city', 'lname'], ascending=[True, True])

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
2   12347    Chris    Smith   chris_smith@email.com   Paris
1   12346     Adam   George   adam_george@email.com    Roma

In [25]:
df.sort_values(by=['city', 'lname'], ascending=[False, False])

   std_id    fname    lname                   email    city
1   12346     Adam   George   adam_george@email.com    Roma
2   12347    Chris    Smith   chris_smith@email.com   Paris
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin

In [26]:
# inplace=True doesn't display the result at the same line we have to run df in the next line nothing change in the sort
df.sort_values(by=['city', 'lname'], ascending=[False, True], inplace=True)

In [27]:
df

   std_id    fname    lname                   email    city
1   12346     Adam   George   adam_george@email.com    Roma
2   12347    Chris    Smith   chris_smith@email.com   Paris
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin

In [29]:
# inplace=False display the result at the sametime this line is run nothing change in the sort
df.sort_values(by=['city', 'lname'], ascending=[False, True], inplace=False)

   std_id    fname    lname                   email    city
1   12346     Adam   George   adam_george@email.com    Roma
2   12347    Chris    Smith   chris_smith@email.com   Paris
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin

In [30]:
df.sort_values(by=['city', 'lname'], ascending=[True, True], inplace=False)

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
2   12347    Chris    Smith   chris_smith@email.com   Paris
1   12346     Adam   George   adam_george@email.com    Roma

In [31]:
df.sort_values(by=['city', 'lname'], ascending=[True, True], inplace=True)

In [32]:
df

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
2   12347    Chris    Smith   chris_smith@email.com   Paris
1   12346     Adam   George   adam_george@email.com    Roma

In [34]:
df.sort_index(ascending=False)

   std_id    fname    lname                   email    city
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
2   12347    Chris    Smith   chris_smith@email.com   Paris
1   12346     Adam   George   adam_george@email.com    Roma
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin

In [35]:
df.sort_index(ascending=True)

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
1   12346     Adam   George   adam_george@email.com    Roma
2   12347    Chris    Smith   chris_smith@email.com   Paris
3   12348     Azad  Abdulla  azad_abdulla@email.com  London

In [36]:
# we sort only one raw
df['lname'].sort_values()

0    Abdulla
3    Abdulla
1     George
2      Smith
Name: lname, dtype: object

In [37]:
# we descending order only one raw
df['lname'].sort_values(ascending=False)

2      Smith
1     George
0    Abdulla
3    Abdulla
Name: lname, dtype: object

In [38]:
# we descending order only one raw
df['fname'].sort_values(ascending=False)

0    Dilshad
2      Chris
3       Azad
1       Adam
Name: fname, dtype: object

In [39]:
# we ascending order only one raw
df['lname'].sort_values(ascending=True)

0    Abdulla
3    Abdulla
1     George
2      Smith
Name: lname, dtype: object

In [40]:
# we ascending order only one raw without using ascending=True 
df['fname'].sort_values()

1       Adam
3       Azad
2      Chris
0    Dilshad
Name: fname, dtype: object

In [42]:
# just to see the table without sort or desort
df

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
2   12347    Chris    Smith   chris_smith@email.com   Paris
1   12346     Adam   George   adam_george@email.com    Roma

In [91]:
# read the data from csv file 
my_df = pd.read_csv('datas/mydata.csv')

In [92]:
my_df

    Unnamed: 0  country    company currency      money  Unnamed: 5
0            0      USA     Google  Dollars  925487847         NaN
1            1   German   Mercides     Euro  587464821         NaN
2            2      USA   Facebook  Dollars  548712498         NaN
3            3       UK        PHP    Pound  254876589         NaN
4            4      USA       .NET  Dollars  654872987         NaN
5            5       UK        NHS  Dollars  356879452         NaN
6            6    Italy  Instagram     Euro  546879514         NaN
7            7  Holland   WhatsApp  Dollars  458796214         NaN
8            8   Greece    Windows        $  325487951  (millions)
9            9    South      Korea  Samsung  658798412  (millions)
10          10      USA         HP  Dollars  658974251         NaN
11          11    Japan      Honda      Yan  365487952         NaN
12          12  Germany        BMW  Dollars  785895898         NaN
13          13  Germany       Audi    Pound  564245478         NaN
14          14  Germany       Volx    Wagen  654781243  (millions)
15          15   France       Ford      Yan  698587433         NaN

In [93]:
my_df.sort_values(by='country', inplace=False)

    Unnamed: 0  country    company currency      money  Unnamed: 5
15          15   France       Ford      Yan  698587433         NaN
1            1   German   Mercides     Euro  587464821         NaN
12          12  Germany        BMW  Dollars  785895898         NaN
13          13  Germany       Audi    Pound  564245478         NaN
14          14  Germany       Volx    Wagen  654781243  (millions)
8            8   Greece    Windows        $  325487951  (millions)
7            7  Holland   WhatsApp  Dollars  458796214         NaN
6            6    Italy  Instagram     Euro  546879514         NaN
11          11    Japan      Honda      Yan  365487952         NaN
9            9    South      Korea  Samsung  658798412  (millions)
3            3       UK        PHP    Pound  254876589         NaN
5            5       UK        NHS  Dollars  356879452         NaN
0            0      USA     Google  Dollars  925487847         NaN
2            2      USA   Facebook  Dollars  548712498         NaN
4            4      USA       .NET  Dollars  654872987         NaN
10          10      USA         HP  Dollars  658974251         NaN

In [61]:
my_df.sort_values(by='country', inplace=True)

In [94]:
my_df

    Unnamed: 0  country    company currency      money  Unnamed: 5
0            0      USA     Google  Dollars  925487847         NaN
1            1   German   Mercides     Euro  587464821         NaN
2            2      USA   Facebook  Dollars  548712498         NaN
3            3       UK        PHP    Pound  254876589         NaN
4            4      USA       .NET  Dollars  654872987         NaN
5            5       UK        NHS  Dollars  356879452         NaN
6            6    Italy  Instagram     Euro  546879514         NaN
7            7  Holland   WhatsApp  Dollars  458796214         NaN
8            8   Greece    Windows        $  325487951  (millions)
9            9    South      Korea  Samsung  658798412  (millions)
10          10      USA         HP  Dollars  658974251         NaN
11          11    Japan      Honda      Yan  365487952         NaN
12          12  Germany        BMW  Dollars  785895898         NaN
13          13  Germany       Audi    Pound  564245478         NaN
14          14  Germany       Volx    Wagen  654781243  (millions)
15          15   France       Ford      Yan  698587433         NaN

In [63]:
my_df['country']

15     France
1      German
12    Germany
13    Germany
14    Germany
8      Greece
7     Holland
6       Italy
11      Japan
9       South
3          UK
5          UK
0         USA
2         USA
4         USA
10        USA
Name: country, dtype: object

In [64]:
my_df['country'].head(11)

15     France
1      German
12    Germany
13    Germany
14    Germany
8      Greece
7     Holland
6       Italy
11      Japan
9       South
3          UK
Name: country, dtype: object

In [65]:
my_df['country'].head(5)

15     France
1      German
12    Germany
13    Germany
14    Germany
Name: country, dtype: object

In [67]:
# if we display multy column we have to put in multilist [[]]
my_df[['country', 'company']]

    country    company
15   France       Ford
1    German   Mercides
12  Germany        BMW
13  Germany       Audi
14  Germany       Volx
8    Greece    Windows
7   Holland   WhatsApp
6     Italy  Instagram
11    Japan      Honda
9     South      Korea
3        UK        PHP
5        UK        NHS
0       USA     Google
2       USA   Facebook
4       USA       .NET
10      USA         HP

In [68]:
# if we display multy column we have to put in multilist [[]]
my_df[['country', 'company', 'currency']]

    country    company currency
15   France       Ford      Yan
1    German   Mercides     Euro
12  Germany        BMW  Dollars
13  Germany       Audi    Pound
14  Germany       Volx    Wagen
8    Greece    Windows       11
7   Holland   WhatsApp  Dollars
6     Italy  Instagram     Euro
11    Japan      Honda      Yan
9     South      Korea  Samsung
3        UK        PHP    Pound
5        UK        NHS  Dollars
0       USA     Google  Dollars
2       USA   Facebook  Dollars
4       USA       .NET  Dollars
10      USA         HP  Dollars

In [78]:
my_df[['country', 'company', 'currency']].head(10)

    country    company currency
15   France       Ford      Yan
1    German   Mercides     Euro
12  Germany        BMW  Dollars
13  Germany       Audi    Pound
14  Germany       Volx    Wagen
8    Greece    Windows       11
7   Holland   WhatsApp  Dollars
6     Italy  Instagram     Euro
11    Japan      Honda      Yan
9     South      Korea  Samsung

In [95]:
my_df.sort_values(by=['country', 'company'], ascending=True)

    Unnamed: 0  country    company currency      money  Unnamed: 5
15          15   France       Ford      Yan  698587433         NaN
1            1   German   Mercides     Euro  587464821         NaN
13          13  Germany       Audi    Pound  564245478         NaN
12          12  Germany        BMW  Dollars  785895898         NaN
14          14  Germany       Volx    Wagen  654781243  (millions)
8            8   Greece    Windows        $  325487951  (millions)
7            7  Holland   WhatsApp  Dollars  458796214         NaN
6            6    Italy  Instagram     Euro  546879514         NaN
11          11    Japan      Honda      Yan  365487952         NaN
9            9    South      Korea  Samsung  658798412  (millions)
5            5       UK        NHS  Dollars  356879452         NaN
3            3       UK        PHP    Pound  254876589         NaN
4            4      USA       .NET  Dollars  654872987         NaN
2            2      USA   Facebook  Dollars  548712498         NaN
0            0      USA     Google  Dollars  925487847         NaN
10          10      USA         HP  Dollars  658974251         NaN

In [96]:
my_df.sort_values(by=['company'], ascending=True)

    Unnamed: 0  country    company currency      money  Unnamed: 5
4            4      USA       .NET  Dollars  654872987         NaN
13          13  Germany       Audi    Pound  564245478         NaN
12          12  Germany        BMW  Dollars  785895898         NaN
2            2      USA   Facebook  Dollars  548712498         NaN
15          15   France       Ford      Yan  698587433         NaN
0            0      USA     Google  Dollars  925487847         NaN
10          10      USA         HP  Dollars  658974251         NaN
11          11    Japan      Honda      Yan  365487952         NaN
6            6    Italy  Instagram     Euro  546879514         NaN
9            9    South      Korea  Samsung  658798412  (millions)
1            1   German   Mercides     Euro  587464821         NaN
5            5       UK        NHS  Dollars  356879452         NaN
3            3       UK        PHP    Pound  254876589         NaN
14          14  Germany       Volx    Wagen  654781243  (millions)
7            7  Holland   WhatsApp  Dollars  458796214         NaN
8            8   Greece    Windows        $  325487951  (millions)

In [97]:
my_df.sort_values(by=['company', 'country'], ascending=[False, True], inplace=True)

In [98]:
my_df

    Unnamed: 0  country    company currency      money  Unnamed: 5
8            8   Greece    Windows        $  325487951  (millions)
7            7  Holland   WhatsApp  Dollars  458796214         NaN
14          14  Germany       Volx    Wagen  654781243  (millions)
3            3       UK        PHP    Pound  254876589         NaN
5            5       UK        NHS  Dollars  356879452         NaN
1            1   German   Mercides     Euro  587464821         NaN
9            9    South      Korea  Samsung  658798412  (millions)
6            6    Italy  Instagram     Euro  546879514         NaN
11          11    Japan      Honda      Yan  365487952         NaN
10          10      USA         HP  Dollars  658974251         NaN
0            0      USA     Google  Dollars  925487847         NaN
15          15   France       Ford      Yan  698587433         NaN
2            2      USA   Facebook  Dollars  548712498         NaN
12          12  Germany        BMW  Dollars  785895898         NaN
13          13  Germany       Audi    Pound  564245478         NaN
4            4      USA       .NET  Dollars  654872987         NaN

In [99]:
my_df.sort_values(by=['company', 'country'], ascending=[True, True], inplace=False)

    Unnamed: 0  country    company currency      money  Unnamed: 5
4            4      USA       .NET  Dollars  654872987         NaN
13          13  Germany       Audi    Pound  564245478         NaN
12          12  Germany        BMW  Dollars  785895898         NaN
2            2      USA   Facebook  Dollars  548712498         NaN
15          15   France       Ford      Yan  698587433         NaN
0            0      USA     Google  Dollars  925487847         NaN
10          10      USA         HP  Dollars  658974251         NaN
11          11    Japan      Honda      Yan  365487952         NaN
6            6    Italy  Instagram     Euro  546879514         NaN
9            9    South      Korea  Samsung  658798412  (millions)
1            1   German   Mercides     Euro  587464821         NaN
5            5       UK        NHS  Dollars  356879452         NaN
3            3       UK        PHP    Pound  254876589         NaN
14          14  Germany       Volx    Wagen  654781243  (millions)
7            7  Holland   WhatsApp  Dollars  458796214         NaN
8            8   Greece    Windows        $  325487951  (millions)

In [100]:
my_df.sort_values(by=['company', 'country']).head(10)

    Unnamed: 0  country    company currency      money  Unnamed: 5
4            4      USA       .NET  Dollars  654872987         NaN
13          13  Germany       Audi    Pound  564245478         NaN
12          12  Germany        BMW  Dollars  785895898         NaN
2            2      USA   Facebook  Dollars  548712498         NaN
15          15   France       Ford      Yan  698587433         NaN
0            0      USA     Google  Dollars  925487847         NaN
10          10      USA         HP  Dollars  658974251         NaN
11          11    Japan      Honda      Yan  365487952         NaN
6            6    Italy  Instagram     Euro  546879514         NaN
9            9    South      Korea  Samsung  658798412  (millions)

In [102]:
my_df['money'].nlargest(10)

0     925487847
12    785895898
15    698587433
10    658974251
9     658798412
4     654872987
14    654781243
1     587464821
13    564245478
2     548712498
Name: money, dtype: int64

In [121]:
my_df.sort_values(by=['company', 'money'], ascending=True)

    Unnamed: 0  country    company currency      money  Unnamed: 5
4            4      USA       .NET  Dollars  654872987         NaN
13          13  Germany       Audi    Pound  564245478         NaN
12          12  Germany        BMW  Dollars  785895898         NaN
2            2      USA   Facebook  Dollars  548712498         NaN
15          15   France       Ford      Yan  698587433         NaN
0            0      USA     Google  Dollars  925487847         NaN
10          10      USA         HP  Dollars  658974251         NaN
11          11    Japan      Honda      Yan  365487952         NaN
6            6    Italy  Instagram     Euro  546879514         NaN
9            9    South      Korea  Samsung  658798412  (millions)
1            1   German   Mercides     Euro  587464821         NaN
5            5       UK        NHS  Dollars  356879452         NaN
3            3       UK        PHP    Pound  254876589         NaN
14          14  Germany       Volx    Wagen  654781243  (millions)
7            7  Holland   WhatsApp  Dollars  458796214         NaN
8            8   Greece    Windows        $  325487951  (millions)

In [128]:
# this is must be money because is an intiger 
my_df.nlargest(15, 'money')

    Unnamed: 0  country    company currency      money  Unnamed: 5
0            0      USA     Google  Dollars  925487847         NaN
12          12  Germany        BMW  Dollars  785895898         NaN
15          15   France       Ford      Yan  698587433         NaN
10          10      USA         HP  Dollars  658974251         NaN
9            9    South      Korea  Samsung  658798412  (millions)
4            4      USA       .NET  Dollars  654872987         NaN
14          14  Germany       Volx    Wagen  654781243  (millions)
1            1   German   Mercides     Euro  587464821         NaN
13          13  Germany       Audi    Pound  564245478         NaN
2            2      USA   Facebook  Dollars  548712498         NaN
6            6    Italy  Instagram     Euro  546879514         NaN
7            7  Holland   WhatsApp  Dollars  458796214         NaN
11          11    Japan      Honda      Yan  365487952         NaN
5            5       UK        NHS  Dollars  356879452         NaN
8            8   Greece    Windows        $  325487951  (millions)

In [130]:
# this is must be money because is an intiger display from lowest moeny
my_df.nsmallest(15, 'money')

    Unnamed: 0  country    company currency      money  Unnamed: 5
3            3       UK        PHP    Pound  254876589         NaN
8            8   Greece    Windows        $  325487951  (millions)
5            5       UK        NHS  Dollars  356879452         NaN
11          11    Japan      Honda      Yan  365487952         NaN
7            7  Holland   WhatsApp  Dollars  458796214         NaN
6            6    Italy  Instagram     Euro  546879514         NaN
2            2      USA   Facebook  Dollars  548712498         NaN
13          13  Germany       Audi    Pound  564245478         NaN
1            1   German   Mercides     Euro  587464821         NaN
14          14  Germany       Volx    Wagen  654781243  (millions)
4            4      USA       .NET  Dollars  654872987         NaN
9            9    South      Korea  Samsung  658798412  (millions)
10          10      USA         HP  Dollars  658974251         NaN
15          15   France       Ford      Yan  698587433         NaN
12          12  Germany        BMW  Dollars  785895898         NaN

In [134]:
my_df['money'].nsmallest(15)

3     254876589
8     325487951
5     356879452
11    365487952
7     458796214
6     546879514
2     548712498
13    564245478
1     587464821
14    654781243
4     654872987
9     658798412
10    658974251
15    698587433
12    785895898
Name: money, dtype: int64