In [4]:
import pandas as pd

In [5]:
students = {
    'std_id': [12345, 12346, 12347, 12348],
    'fname': ['Dilshad', 'Adam', 'Chris', 'Azad'],
    'lname': ['Abdulla', 'George', 'Smith', 'Abdulla'],
    'email': ['dilshad.a73@email.com', 'adam_george@email.com', 'chris_smith@email.com', 'azad_abdulla@email.com'],
    'city': ['Berlin', 'Roma', 'Paris', 'London']
}

In [6]:
df = pd.DataFrame(students)

In [7]:
df

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
1   12346     Adam   George   adam_george@email.com    Roma
2   12347    Chris    Smith   chris_smith@email.com   Paris
3   12348     Azad  Abdulla  azad_abdulla@email.com  London

In [8]:
# sorting by last name
df.sort_values(by='lname')

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
1   12346     Adam   George   adam_george@email.com    Roma
2   12347    Chris    Smith   chris_smith@email.com   Paris

In [9]:
# sorting by first name
df.sort_values(by='fname')

   std_id    fname    lname                   email    city
1   12346     Adam   George   adam_george@email.com    Roma
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
2   12347    Chris    Smith   chris_smith@email.com   Paris
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin

In [10]:
df.sort_values(by='std_id')

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
1   12346     Adam   George   adam_george@email.com    Roma
2   12347    Chris    Smith   chris_smith@email.com   Paris
3   12348     Azad  Abdulla  azad_abdulla@email.com  London

In [11]:
# Desending order like reverse
df.sort_values(by='lname', ascending=False)

   std_id    fname    lname                   email    city
2   12347    Chris    Smith   chris_smith@email.com   Paris
1   12346     Adam   George   adam_george@email.com    Roma
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
3   12348     Azad  Abdulla  azad_abdulla@email.com  London

In [12]:
# Desending order like reverse
df.sort_values(by='fname', ascending=False)

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
2   12347    Chris    Smith   chris_smith@email.com   Paris
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
1   12346     Adam   George   adam_george@email.com    Roma

In [13]:
# Desending order like reverse
df.sort_values(by='std_id', ascending=False)

   std_id    fname    lname                   email    city
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
2   12347    Chris    Smith   chris_smith@email.com   Paris
1   12346     Adam   George   adam_george@email.com    Roma
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin

In [14]:
# Desending order like reverse
df.sort_values(by='email', ascending=False)

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
2   12347    Chris    Smith   chris_smith@email.com   Paris
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
1   12346     Adam   George   adam_george@email.com    Roma

In [15]:
# Change ascending order to True it will display by order 
df.sort_values(by='email', ascending=True)

   std_id    fname    lname                   email    city
1   12346     Adam   George   adam_george@email.com    Roma
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
2   12347    Chris    Smith   chris_smith@email.com   Paris
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin

In [16]:
# Desending order like reverse
df.sort_values(by=['lname', 'fname'], ascending=False)

   std_id    fname    lname                   email    city
2   12347    Chris    Smith   chris_smith@email.com   Paris
1   12346     Adam   George   adam_george@email.com    Roma
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
3   12348     Azad  Abdulla  azad_abdulla@email.com  London

In [17]:
# Desending order like reverse
df.sort_values(by=['lname', 'fname'], ascending=True)

   std_id    fname    lname                   email    city
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
1   12346     Adam   George   adam_george@email.com    Roma
2   12347    Chris    Smith   chris_smith@email.com   Paris

In [18]:
# Desending order like reverse
df.sort_values(by=['lname', 'fname', 'city'], ascending=True)

   std_id    fname    lname                   email    city
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
1   12346     Adam   George   adam_george@email.com    Roma
2   12347    Chris    Smith   chris_smith@email.com   Paris

In [19]:
# Desending order like reverse
df.sort_values(by=['city', 'lname', 'fname'], ascending=True)

   std_id    fname    lname                   email    city
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
3   12348     Azad  Abdulla  azad_abdulla@email.com  London
2   12347    Chris    Smith   chris_smith@email.com   Paris
1   12346     Adam   George   adam_george@email.com    Roma

In [20]:
# Desending order like reverse
df.sort_values(by=['lname', 'fname'], ascending=False)

   std_id    fname    lname                   email    city
2   12347    Chris    Smith   chris_smith@email.com   Paris
1   12346     Adam   George   adam_george@email.com    Roma
0   12345  Dilshad  Abdulla   dilshad.a73@email.com  Berlin
3   12348     Azad  Abdulla  azad_abdulla@email.com  London

In [23]:
df.append(fname='Claudia', lname='Paul')

AttributeError: 'DataFrame' object has no attribute 'append'